import LeanProofs.Flux.VC.CollectionsRingBufferVecQueuePopCorrect
import LeanProofs.User.Proof.CollectionsRingBufferVecQueuePopCorrectProof

#check (F.CollectionsRingBufferVecQueuePopCorrect_proof : F.CollectionsRingBufferVecQueuePopCorrect)
